// Code generated by @apexlang/codegen. DO NOT EDIT.

package iotacsv

import (
	"context"

	"github.com/nanobus/iota/go/rx/flux"
)

type ns struct{}

func (n *ns) Namespace() string {
	return "csv.v1"
}

type CSV interface {
	Parse(ctx context.Context, options *Options, input flux.Flux[[]byte]) flux.Flux[map[string]string]
}

type Options struct {
	ns
	Delimiter     string `json:"delimiter" yaml:"delimiter" msgpack:"delimiter"`
	Quote_char    string `json:"quote_char" yaml:"quote_char" msgpack:"quote_char"`
	Row_separator string `json:"row_separator" yaml:"row_separator" msgpack:"row_separator"`
	Escape_char   string `json:"escape_char" yaml:"escape_char" msgpack:"escape_char"`
	Header_row    bool   `json:"header_row" yaml:"header_row" msgpack:"header_row"`
}

func (o *Options) Type() string {
	return "Options"
}
