[package]
name = "rand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
strip = "symbols"
codegen-units = 1
debug = false
lto = true
opt-level = "z"
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
wick-component = { git = "https://github.com/candlecorp/wick.git" }
wasmrs-guest = { version = "*", features = [] }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
rand = { version = "0.8", default-features = false, features = ["small_rng"] }

[build-dependencies]
wick-component-codegen = { git = "https://github.com/candlecorp/wick.git" }
