version: '3'

services:
  postgres-container:
    image: postgres
    container_name: postgres-container-oauth
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oauth
    volumes:
      - ./db:/docker-entrypoint-initdb.d
