project_name := "oauth"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/oauth.wasm oauth.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/oauth.wasm oauth.wick
setup:
    mkdir -p build
test: build
    wick test oauth.wick
clean:
  cargo clean
