project_name := "object"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm object.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm object.wick
setup:
    mkdir -p build
clean:
  cargo clean
test:
  wick test object.wick
publish:
  wick reg push object.wick