project_name := "usps"
root_dir:=`cargo metadata --format-version=1 |wick query --type json -r '.workspace_root'`
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp {{root_dir}}/target/wasm32-unknown-unknown/release/{{project_name}}.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm usps-engine.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp {{root_dir}}/target/wasm32-wasi/debug/{{project_name}}.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm usps-engine.wick
setup:
    mkdir -p build
test:
    wick test usps-engine.wick
clean:
  cargo clean
