[package]
name = "liquid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
strip = "symbols"
codegen-units = 1
debug = false
lto = true
opt-level = "z"
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
# wick-component = "0.15"
wick-component = { path = "/Users/fshaikh/Developer/candlecorp/wick/crates/wick/wick-component" }
wasmrs-guest = { version = "0.11", features = [] }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
liquid = "0.26"
serde_json = "1"

[build-dependencies]
# wick-component-codegen = { version = "*" }
wick-component-codegen = { path = "/Users/fshaikh/Developer/candlecorp/wick/crates/wick/wick-component-codegen" }
