project_name := "liquid"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm liquid.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm liquid.wick
setup:
    mkdir -p build
test:
  wick test liquid.wick
clean:
  cargo clean
