project_name := "liquid"
root_dir:=`cargo metadata --format-version=1 |wick query --type json -r '.workspace_root'`
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp {{root_dir}}/target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm liquid.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp {{root_dir}}/target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm liquid.wick
setup:
    mkdir -p build
test:
  wick test liquid.wick
clean:
  cargo clean
publish:
  wick reg push liquid.wick