project_name := "jinja"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm component.yaml
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm component.yaml
setup:
    mkdir -p build
test:
  wick test component.yaml
clean:
  cargo clean
publish:
  wick reg push component.yaml